services:
    mattermost:
        # This can be updated with docker tags from https://hub.docker.com/r/mattermost/mattermost-enterprise-edition/tags
        image: mattermost/mattermost-enterprise-edition:release-7.7

        ports:
            - "8066:8066"
        environment:
            MM_SQLSETTINGS_DRIVERNAME: postgres
            MM_SQLSETTINGS_DATASOURCE: "postgres://mmuser:mostest@db/mattermost_test?sslmode=disable\u0026connect_timeout=10"
            MM_SERVICESETTINGS_LISTENADDRESS: ":8066"
            MM_SERVICESETTINGS_SITEURL: "http://localhost:8066"
            MM_SERVICESETTINGS_ENABLEOAUTHSERVICEPROVIDER: "true"
            MM_SERVICESETTINGS_ENABLEDEVELOPER: "true"
            MM_SERVICESETTINGS_ENABLETESTING: "true"
            MM_PLUGINSETTINGS_AUTOMATICPREPACKAGEDPLUGINS: "true"
            MM_PLUGINSETTINGS_ENABLEUPLOADS: "true"
            MM_FEATUREFLAGS_AppsEnabled: "true"
            MM_ADMIN_USERNAME: "bill" 
            MM_ADMIN_PASSWORD: "123"
            MM_SERVICESETTINGS_ALLOWEDUNTRUSTEDINTERNALCONNECTIONS: "172.18.0.1"
            MM_SERVICESETTINGS_ENABLEBOTACCOUNTCREATION: "true"

            # This can be updated with release versions from https://github.com/mattermost/mattermost-plugin-apps/releases
            MM_FEATUREFLAGS_PluginApps: "1.2.0"

            MM_LOGSETTINGS_CONSOLELEVEL: DEBUG
            MM_LOGSETTINGS_FILELEVEL: DEBUG
    db:
        image: postgres
        ports:
            - "5433:5432"
        environment:
            POSTGRES_PASSWORD: mostest
            POSTGRES_USER: mmuser
            POSTGRES_DB: mattermost_test
